import { TranslatedQuizQuestion } from '../../quizTranslations';

export const environmentComprehensiveQuestions: TranslatedQuizQuestion[] = [
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce reprezintă standardul de emisii Euro 6d pentru camioane?",
      de: "Was bedeutet der Euro 6d-Emissionsstandard für LKW?",
      en: "What does the Euro 6d emission standard represent for trucks?"
    },
    options: {
      ro: ["Standard opțional", "Cel mai strict standard actual UE pentru emisii NOx și particule", "Standard vechi", "Doar pentru mașini"],
      de: ["Optionaler Standard", "Strengster aktueller EU-Standard für NOx- und Partikelemissionen", "Alter Standard", "Nur für PKW"],
      en: ["Optional standard", "Strictest current EU standard for NOx and particle emissions", "Old standard", "Only for cars"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Euro 6d este cel mai strict standard actual, cu limite severe pentru NOx (0.4g/kWh) și particule.",
      de: "Euro 6d ist der strengste aktuelle Standard mit strengen Grenzwerten für NOx (0,4g/kWh) und Partikel.",
      en: "Euro 6d is the strictest current standard with severe limits for NOx (0.4g/kWh) and particles."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce este amprenta de carbon (carbon footprint) în transport?",
      de: "Was ist der CO2-Fußabdruck (Carbon Footprint) im Transport?",
      en: "What is the carbon footprint in transport?"
    },
    options: {
      ro: ["Urmele anvelopelor", "Totalul emisiilor de CO2 generate de activitatea de transport", "Marca camionului", "Consumul de combustibil"],
      de: ["Reifenspuren", "Gesamte CO2-Emissionen der Transportaktivität", "LKW-Marke", "Kraftstoffverbrauch"],
      en: ["Tire tracks", "Total CO2 emissions generated by transport activity", "Truck brand", "Fuel consumption"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Amprenta de carbon = toate emisiile de CO2 asociate cu transportul, de la producție combustibil până la livrare.",
      de: "CO2-Fußabdruck = alle mit dem Transport verbundenen CO2-Emissionen, von der Kraftstoffproduktion bis zur Lieferung.",
      en: "Carbon footprint = all CO2 emissions associated with transport, from fuel production to delivery."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Cum se calculează emisiile de CO2 pentru un transport rutier?",
      de: "Wie berechnet man die CO2-Emissionen für einen Straßentransport?",
      en: "How do you calculate CO2 emissions for road transport?"
    },
    options: {
      ro: ["Nu se poate calcula", "Consum combustibil (L) × factor emisie (kg CO2/L) sau tkm × factor emisie", "Doar estimare", "După greutate"],
      de: ["Kann nicht berechnet werden", "Kraftstoffverbrauch (L) × Emissionsfaktor (kg CO2/L) oder tkm × Emissionsfaktor", "Nur Schätzung", "Nach Gewicht"],
      en: ["Cannot be calculated", "Fuel consumption (L) × emission factor (kg CO2/L) or tkm × emission factor", "Only estimation", "By weight"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Calcul: litri diesel × 2.67 kg CO2/L sau tone-km × factor standard (ex: 62g CO2/tkm).",
      de: "Berechnung: Liter Diesel × 2,67 kg CO2/L oder Tonnen-km × Standardfaktor (z.B. 62g CO2/tkm).",
      en: "Calculation: liters diesel × 2.67 kg CO2/L or tonne-km × standard factor (e.g., 62g CO2/tkm)."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce este AdBlue și de ce este necesar pentru camioanele Euro 6?",
      de: "Was ist AdBlue und warum ist es für Euro 6-LKW erforderlich?",
      en: "What is AdBlue and why is it needed for Euro 6 trucks?"
    },
    options: {
      ro: ["Colorant", "Soluție de uree pentru reducerea NOx în sistemul SCR", "Antigel", "Ulei motor"],
      de: ["Farbstoff", "Harnstofflösung zur NOx-Reduktion im SCR-System", "Frostschutzmittel", "Motoröl"],
      en: ["Dye", "Urea solution for NOx reduction in SCR system", "Antifreeze", "Engine oil"]
    },
    correctIndex: 1,
    explanation: {
      ro: "AdBlue (32.5% uree) este injectat în gazele de eșapament pentru a reduce NOx cu 90% în sistemul SCR.",
      de: "AdBlue (32,5% Harnstoff) wird in Abgase eingespritzt, um NOx im SCR-System um 90% zu reduzieren.",
      en: "AdBlue (32.5% urea) is injected into exhaust gases to reduce NOx by 90% in the SCR system."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Client cere raport de sustenabilitate pentru 100 curse RO-DE anual. Ce date și calcule sunt necesare?",
      de: "Kunde fordert Nachhaltigkeitsbericht für 100 RO-DE Fahrten jährlich. Welche Daten und Berechnungen sind erforderlich?",
      en: "Client requests sustainability report for 100 RO-DE trips annually. What data and calculations are needed?"
    },
    options: {
      ro: ["Doar km", "Consum total, emisii CO2/NOx/PM, comparație modal, carbon offset opțiuni, certificare", "Doar facturile", "Doar greutate"],
      de: ["Nur km", "Gesamtverbrauch, CO2/NOx/PM-Emissionen, Modalvergleich, Carbon-Offset-Optionen, Zertifizierung", "Nur Rechnungen", "Nur Gewicht"],
      en: ["Only km", "Total consumption, CO2/NOx/PM emissions, modal comparison, carbon offset options, certification", "Only invoices", "Only weight"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Raport sustenabilitate: consum, emisii detaliate, benchmark vs. alte moduri, opțiuni compensare carbon, certificări.",
      de: "Nachhaltigkeitsbericht: Verbrauch, detaillierte Emissionen, Benchmark vs. andere Modi, Carbon-Offset-Optionen, Zertifizierungen.",
      en: "Sustainability report: consumption, detailed emissions, benchmark vs. other modes, carbon offset options, certifications."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este eco-driving și ce economii poate genera?",
      de: "Was ist Eco-Driving und welche Einsparungen kann es erzielen?",
      en: "What is eco-driving and what savings can it generate?"
    },
    options: {
      ro: ["Conducere lentă", "Tehnici de conducere eficientă: 5-15% reducere consum și emisii", "Conducere electrică", "Conducere nocturnă"],
      de: ["Langsames Fahren", "Effiziente Fahrtechniken: 5-15% Verbrauchs- und Emissionsreduzierung", "Elektrisches Fahren", "Nachtfahren"],
      en: ["Slow driving", "Efficient driving techniques: 5-15% consumption and emission reduction", "Electric driving", "Night driving"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Eco-driving: accelerare lină, viteză constantă, anticipare, folosire inerție. Economie 5-15% combustibil.",
      de: "Eco-Driving: sanftes Beschleunigen, konstante Geschwindigkeit, Vorausschau, Nutzung der Trägheit. 5-15% Kraftstoffersparnis.",
      en: "Eco-driving: smooth acceleration, constant speed, anticipation, use of inertia. 5-15% fuel savings."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce combustibili alternativi există pentru camioane?",
      de: "Welche alternativen Kraftstoffe gibt es für LKW?",
      en: "What alternative fuels exist for trucks?"
    },
    options: {
      ro: ["Doar diesel", "LNG, CNG, HVO, biodiesel, hidrogen, electric", "Doar benzină", "Doar GPL"],
      de: ["Nur Diesel", "LNG, CNG, HVO, Biodiesel, Wasserstoff, elektrisch", "Nur Benzin", "Nur LPG"],
      en: ["Only diesel", "LNG, CNG, HVO, biodiesel, hydrogen, electric", "Only petrol", "Only LPG"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Alternative: LNG/CNG (gaz), HVO (diesel sintetic), biodiesel, hidrogen (fuel cell), electric (baterie).",
      de: "Alternativen: LNG/CNG (Gas), HVO (synthetischer Diesel), Biodiesel, Wasserstoff (Brennstoffzelle), elektrisch (Batterie).",
      en: "Alternatives: LNG/CNG (gas), HVO (synthetic diesel), biodiesel, hydrogen (fuel cell), electric (battery)."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Flotă de 20 camioane Euro 5. Client cere reducere 30% emisii în 3 ani. Opțiuni strategice?",
      de: "Flotte von 20 Euro 5-LKW. Kunde fordert 30% Emissionsreduktion in 3 Jahren. Strategische Optionen?",
      en: "Fleet of 20 Euro 5 trucks. Client requests 30% emission reduction in 3 years. Strategic options?"
    },
    options: {
      ro: ["Imposibil", "Înlocuire treptată cu Euro 6/LNG + eco-driving training + optimizare rute + carbon offsetting", "Doar vopsea verde", "Doar reducere km"],
      de: ["Unmöglich", "Schrittweiser Austausch auf Euro 6/LNG + Eco-Driving-Training + Routenoptimierung + Carbon Offsetting", "Nur grüne Farbe", "Nur km-Reduktion"],
      en: ["Impossible", "Gradual replacement with Euro 6/LNG + eco-driving training + route optimization + carbon offsetting", "Only green paint", "Only km reduction"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Plan 30%: înlocuire 7-10 camioane Euro 6/LNG, training eco-driving (-10%), optimizare rute (-5%), carbon offset rest.",
      de: "30%-Plan: 7-10 LKW Euro 6/LNG ersetzen, Eco-Driving-Training (-10%), Routenoptimierung (-5%), Carbon Offset Rest.",
      en: "30% plan: replace 7-10 trucks Euro 6/LNG, eco-driving training (-10%), route optimization (-5%), carbon offset remainder."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este HVO și care sunt avantajele față de diesel convențional?",
      de: "Was ist HVO und welche Vorteile hat es gegenüber konventionellem Diesel?",
      en: "What is HVO and what are its advantages over conventional diesel?"
    },
    options: {
      ro: ["Ulei motor", "Diesel sintetic din uleiuri vegetale: -90% CO2, compatibil motoare diesel standard", "Benzină premium", "Antigel"],
      de: ["Motoröl", "Synthetischer Diesel aus Pflanzenölen: -90% CO2, kompatibel mit Standard-Dieselmotoren", "Premium-Benzin", "Frostschutzmittel"],
      en: ["Engine oil", "Synthetic diesel from vegetable oils: -90% CO2, compatible with standard diesel engines", "Premium petrol", "Antifreeze"]
    },
    correctIndex: 1,
    explanation: {
      ro: "HVO (Hydrotreated Vegetable Oil): diesel sintetic, reduce CO2 cu 90%, nu necesită modificări motor.",
      de: "HVO (hydriertes Pflanzenöl): synthetischer Diesel, reduziert CO2 um 90%, keine Motormodifikationen erforderlich.",
      en: "HVO (Hydrotreated Vegetable Oil): synthetic diesel, reduces CO2 by 90%, no engine modifications needed."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce este certificarea ISO 14001 pentru companii de transport?",
      de: "Was ist die ISO 14001-Zertifizierung für Transportunternehmen?",
      en: "What is ISO 14001 certification for transport companies?"
    },
    options: {
      ro: ["Certificat de calitate", "Sistem de management de mediu certificat internațional", "Licență transport", "Asigurare"],
      de: ["Qualitätszertifikat", "International zertifiziertes Umweltmanagementsystem", "Transportlizenz", "Versicherung"],
      en: ["Quality certificate", "Internationally certified environmental management system", "Transport license", "Insurance"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ISO 14001: standard internațional pentru managementul de mediu, demonstrează angajamentul pentru sustenabilitate.",
      de: "ISO 14001: internationaler Standard für Umweltmanagement, zeigt Engagement für Nachhaltigkeit.",
      en: "ISO 14001: international standard for environmental management, demonstrates sustainability commitment."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Transport LNG vs. diesel pe rută RO-DE (1500km). Comparație costuri și emisii?",
      de: "LNG- vs. Diesel-Transport auf Route RO-DE (1500km). Kosten- und Emissionsvergleich?",
      en: "LNG vs. diesel transport on RO-DE route (1500km). Cost and emission comparison?"
    },
    options: {
      ro: ["Identice", "LNG: -20% CO2, -90% NOx, cost similar sau ușor mai mic, dar investiție vehicul mai mare", "LNG mai scump", "Diesel mai curat"],
      de: ["Identisch", "LNG: -20% CO2, -90% NOx, ähnliche oder leicht niedrigere Kosten, aber höhere Fahrzeuginvestition", "LNG teurer", "Diesel sauberer"],
      en: ["Identical", "LNG: -20% CO2, -90% NOx, similar or slightly lower cost, but higher vehicle investment", "LNG more expensive", "Diesel cleaner"]
    },
    correctIndex: 1,
    explanation: {
      ro: "LNG: -20% CO2, -90% NOx, cost/km comparabil, dar camion LNG costă 30-50% mai mult decât diesel echivalent.",
      de: "LNG: -20% CO2, -90% NOx, vergleichbare Kosten/km, aber LNG-LKW kostet 30-50% mehr als Diesel-Äquivalent.",
      en: "LNG: -20% CO2, -90% NOx, comparable cost/km, but LNG truck costs 30-50% more than diesel equivalent."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este sistemul ETS (Emissions Trading System) și cum afectează transportul?",
      de: "Was ist das ETS (Emissionshandelssystem) und wie beeinflusst es den Transport?",
      en: "What is the ETS (Emissions Trading System) and how does it affect transport?"
    },
    options: {
      ro: ["Sistem GPS", "Piață de certificate de emisii CO2, va include transportul rutier din 2027", "Taxă de drum", "Asigurare"],
      de: ["GPS-System", "CO2-Zertifikate-Markt, wird Straßentransport ab 2027 einschließen", "Straßengebühr", "Versicherung"],
      en: ["GPS system", "CO2 certificate market, will include road transport from 2027", "Road toll", "Insurance"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ETS II: din 2027 transportul rutier va fi inclus în piața de emisii UE, crescând costul combustibililor fosili.",
      de: "ETS II: Ab 2027 wird Straßentransport in den EU-Emissionsmarkt aufgenommen, was die Kosten fossiler Kraftstoffe erhöht.",
      en: "ETS II: from 2027 road transport will be included in EU emissions market, increasing fossil fuel costs."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce măsuri pot reduce zgomotul camioanelor în zone urbane?",
      de: "Welche Maßnahmen können den LKW-Lärm in städtischen Gebieten reduzieren?",
      en: "What measures can reduce truck noise in urban areas?"
    },
    options: {
      ro: ["Nicio măsură posibilă", "Anvelope silențioase, livrări noapte cu vehicule electrice, reducere viteză", "Doar claxon mai mic", "Doar muzică"],
      de: ["Keine Maßnahme möglich", "Leise Reifen, Nachtlieferungen mit Elektrofahrzeugen, Geschwindigkeitsreduzierung", "Nur kleinere Hupe", "Nur Musik"],
      en: ["No measure possible", "Silent tyres, night deliveries with electric vehicles, speed reduction", "Only smaller horn", "Only music"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Reducere zgomot: anvelope cu marcaj S (silent), vehicule electrice pentru livrări urbane, viteze reduse.",
      de: "Lärmreduzierung: Reifen mit S-Kennzeichnung (leise), Elektrofahrzeuge für städtische Lieferungen, reduzierte Geschwindigkeiten.",
      en: "Noise reduction: tyres with S marking (silent), electric vehicles for urban deliveries, reduced speeds."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Client retail cere zero-emission last-mile în centrul orașului. Soluții tehnice și economice?",
      de: "Einzelhandelskunde fordert Zero-Emission Last-Mile in der Innenstadt. Technische und wirtschaftliche Lösungen?",
      en: "Retail client requests zero-emission last-mile in city center. Technical and economic solutions?"
    },
    options: {
      ro: ["Imposibil", "Van-uri electrice + micro-hub urban + cargo bikes pentru colete mici + consolidare încărcături", "Doar biciclete", "Doar drone"],
      de: ["Unmöglich", "Elektro-Transporter + urbaner Mikro-Hub + Cargo-Bikes für kleine Pakete + Ladungskonsolidierung", "Nur Fahrräder", "Nur Drohnen"],
      en: ["Impossible", "Electric vans + urban micro-hub + cargo bikes for small parcels + load consolidation", "Only bicycles", "Only drones"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Zero-emission: hub periferie → van electric → micro-hub urban → cargo bikes. Consolidare pentru eficiență.",
      de: "Zero-Emission: Vorort-Hub → Elektro-Van → urbaner Mikro-Hub → Cargo-Bikes. Konsolidierung für Effizienz.",
      en: "Zero-emission: suburban hub → electric van → urban micro-hub → cargo bikes. Consolidation for efficiency."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este GLEC Framework pentru raportarea emisiilor în transport?",
      de: "Was ist das GLEC Framework für die Emissionsberichterstattung im Transport?",
      en: "What is the GLEC Framework for emission reporting in transport?"
    },
    options: {
      ro: ["Aplicație GPS", "Metodologie standardizată pentru calculul și raportarea emisiilor logistice", "Asigurare", "Taxă de drum"],
      de: ["GPS-App", "Standardisierte Methodik zur Berechnung und Berichterstattung von Logistikemissionen", "Versicherung", "Straßengebühr"],
      en: ["GPS app", "Standardized methodology for calculating and reporting logistics emissions", "Insurance", "Road toll"]
    },
    correctIndex: 1,
    explanation: {
      ro: "GLEC (Global Logistics Emissions Council): metodologie globală standardizată pentru emisii în logistică, bază pentru ISO 14083.",
      de: "GLEC (Global Logistics Emissions Council): global standardisierte Methodik für Logistikemissionen, Grundlage für ISO 14083.",
      en: "GLEC (Global Logistics Emissions Council): globally standardized methodology for logistics emissions, basis for ISO 14083."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce avantaje oferă camioanele electrice pentru distribuție urbană?",
      de: "Welche Vorteile bieten Elektro-LKW für die städtische Verteilung?",
      en: "What advantages do electric trucks offer for urban distribution?"
    },
    options: {
      ro: ["Niciun avantaj", "Zero emisii locale, zgomot redus, acces în LEZ, costuri operaționale mai mici", "Doar pentru distanțe lungi", "Mai poluante"],
      de: ["Kein Vorteil", "Null lokale Emissionen, weniger Lärm, Zugang zu LEZ, niedrigere Betriebskosten", "Nur für lange Strecken", "Mehr verschmutzend"],
      en: ["No advantage", "Zero local emissions, reduced noise, LEZ access, lower operating costs", "Only for long distances", "More polluting"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Electrice urban: zero emisii, acces toate zonele, livrări noapte (silențios), cost/km mai mic.",
      de: "Elektrisch urban: null Emissionen, Zugang zu allen Zonen, Nachtlieferungen (leise), niedrigere Kosten/km.",
      en: "Electric urban: zero emissions, all-zone access, night deliveries (silent), lower cost/km."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Calculează emisiile CO2 pentru transport 20t marfă RO-DE (1500km) cu camion diesel 35L/100km.",
      de: "Berechne die CO2-Emissionen für 20t Frachttransport RO-DE (1500km) mit Diesel-LKW 35L/100km.",
      en: "Calculate CO2 emissions for 20t freight transport RO-DE (1500km) with diesel truck 35L/100km."
    },
    options: {
      ro: ["500 kg", "1400 kg CO2", "2000 kg", "100 kg"],
      de: ["500 kg", "1400 kg CO2", "2000 kg", "100 kg"],
      en: ["500 kg", "1400 kg CO2", "2000 kg", "100 kg"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Calcul: 1500km × 35L/100km = 525L diesel. 525L × 2.67kg CO2/L = 1402 kg CO2 ≈ 1400 kg.",
      de: "Berechnung: 1500km × 35L/100km = 525L Diesel. 525L × 2,67kg CO2/L = 1402 kg CO2 ≈ 1400 kg.",
      en: "Calculation: 1500km × 35L/100km = 525L diesel. 525L × 2.67kg CO2/L = 1402 kg CO2 ≈ 1400 kg."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este carbon offsetting în transport și cum funcționează?",
      de: "Was ist Carbon Offsetting im Transport und wie funktioniert es?",
      en: "What is carbon offsetting in transport and how does it work?"
    },
    options: {
      ro: ["Reducere directă emisii", "Compensare emisii prin investiții în proiecte de captare/reducere CO2", "Taxă de drum", "Schimbare combustibil"],
      de: ["Direkte Emissionsreduktion", "Emissionskompensation durch Investitionen in CO2-Abscheidungs-/Reduktionsprojekte", "Straßengebühr", "Kraftstoffwechsel"],
      en: ["Direct emission reduction", "Emission compensation through investments in CO2 capture/reduction projects", "Road toll", "Fuel change"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Carbon offsetting: compensare emisii inevitabile prin achiziție credite carbon (proiecte păduri, energii regenerabile).",
      de: "Carbon Offsetting: Kompensation unvermeidbarer Emissionen durch Kauf von CO2-Gutschriften (Wald-, Erneuerbare-Energie-Projekte).",
      en: "Carbon offsetting: compensating unavoidable emissions through carbon credit purchase (forest, renewable energy projects)."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce impact are viteza asupra consumului de combustibil?",
      de: "Welchen Einfluss hat die Geschwindigkeit auf den Kraftstoffverbrauch?",
      en: "What impact does speed have on fuel consumption?"
    },
    options: {
      ro: ["Niciun impact", "Viteza optimă 60-80 km/h; peste 85 km/h consumul crește exponențial", "Viteză mare = consum mic", "Doar în oraș contează"],
      de: ["Kein Einfluss", "Optimale Geschwindigkeit 60-80 km/h; über 85 km/h steigt Verbrauch exponentiell", "Hohe Geschwindigkeit = niedriger Verbrauch", "Nur in der Stadt wichtig"],
      en: ["No impact", "Optimal speed 60-80 km/h; above 85 km/h consumption increases exponentially", "High speed = low consumption", "Only matters in city"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Consum optim la 60-80 km/h. La 90 km/h vs. 80 km/h: +10-15% consum din cauza rezistenței aerului.",
      de: "Optimaler Verbrauch bei 60-80 km/h. Bei 90 km/h vs. 80 km/h: +10-15% Verbrauch durch Luftwiderstand.",
      en: "Optimal consumption at 60-80 km/h. At 90 km/h vs. 80 km/h: +10-15% consumption due to air resistance."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Implementare strategie net-zero pentru flotă de 50 camioane până în 2035. Plan de acțiune?",
      de: "Implementierung einer Net-Zero-Strategie für 50-LKW-Flotte bis 2035. Aktionsplan?",
      en: "Implementing net-zero strategy for 50-truck fleet by 2035. Action plan?"
    },
    options: {
      ro: ["Imposibil", "2024-27: Euro 6/LNG; 2027-30: 30% electric; 2030-35: 70% electric/H2 + offset restul", "Doar offset", "Doar electric"],
      de: ["Unmöglich", "2024-27: Euro 6/LNG; 2027-30: 30% elektrisch; 2030-35: 70% elektrisch/H2 + Offset Rest", "Nur Offset", "Nur elektrisch"],
      en: ["Impossible", "2024-27: Euro 6/LNG; 2027-30: 30% electric; 2030-35: 70% electric/H2 + offset remainder", "Only offset", "Only electric"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Net-zero 2035: tranziție treptată diesel→LNG→electric/H2, infrastructură încărcare, training, carbon offset pentru restul.",
      de: "Net-Zero 2035: schrittweiser Übergang Diesel→LNG→elektrisch/H2, Ladeinfrastruktur, Training, Carbon Offset für Rest.",
      en: "Net-zero 2035: gradual transition diesel→LNG→electric/H2, charging infrastructure, training, carbon offset for remainder."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este aerodinamica camioanelor și cum afectează consumul?",
      de: "Was ist LKW-Aerodynamik und wie beeinflusst sie den Verbrauch?",
      en: "What is truck aerodynamics and how does it affect consumption?"
    },
    options: {
      ro: ["Nu contează", "Deflectoare, carenaje laterale, cozi aerodinamice reduc consumul cu 5-15%", "Doar estetică", "Doar pentru curse"],
      de: ["Spielt keine Rolle", "Deflektoren, Seitenverkleidungen, Aero-Hecks reduzieren Verbrauch um 5-15%", "Nur Ästhetik", "Nur für Rennen"],
      en: ["Doesn't matter", "Deflectors, side skirts, aero tails reduce consumption by 5-15%", "Only aesthetics", "Only for racing"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Îmbunătățiri aero: deflectoare cabină, carenaje laterale, cozi aerodinamice economisesc 5-15% combustibil la viteze autostrăzi.",
      de: "Aero-Verbesserungen: Kabinendeflektoren, Seitenverkleidungen, Aero-Hecks sparen 5-15% Kraftstoff bei Autobahngeschwindigkeiten.",
      en: "Aero improvements: cab deflectors, side skirts, aero tails save 5-15% fuel at motorway speeds."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce reglementări UE vizează reducerea emisiilor din transport rutier?",
      de: "Welche EU-Vorschriften zielen auf die Reduzierung der Emissionen im Straßentransport ab?",
      en: "What EU regulations target emission reduction from road transport?"
    },
    options: {
      ro: ["Nicio reglementare", "Standarde Euro, CO2 pentru vehicule grele, Fit for 55, ETS II", "Doar Euro", "Doar taxe"],
      de: ["Keine Vorschriften", "Euro-Standards, CO2 für schwere Fahrzeuge, Fit for 55, ETS II", "Nur Euro", "Nur Steuern"],
      en: ["No regulations", "Euro standards, CO2 for heavy vehicles, Fit for 55, ETS II", "Only Euro", "Only taxes"]
    },
    correctIndex: 1,
    explanation: {
      ro: "UE: Euro 6/7 (poluanți locali), CO2 HDV (-30% 2030), Fit for 55, ETS II (2027), AFIR (infrastructură).",
      de: "EU: Euro 6/7 (lokale Schadstoffe), CO2 HDV (-30% 2030), Fit for 55, ETS II (2027), AFIR (Infrastruktur).",
      en: "EU: Euro 6/7 (local pollutants), CO2 HDV (-30% 2030), Fit for 55, ETS II (2027), AFIR (infrastructure)."
    }
  },
  {
    difficultyLevel: 5,
    question: {
      ro: "Comparație TCO (Total Cost of Ownership) pe 5 ani: diesel vs. electric pentru livrări urbane 100km/zi.",
      de: "TCO-Vergleich (Total Cost of Ownership) über 5 Jahre: Diesel vs. elektrisch für städtische Lieferungen 100km/Tag.",
      en: "TCO (Total Cost of Ownership) comparison over 5 years: diesel vs. electric for urban deliveries 100km/day."
    },
    options: {
      ro: ["Diesel mai ieftin mereu", "Electric: achiziție mai mare dar operare -40%, TCO similar sau mai mic la 5 ani", "Identic", "Electric de 3x mai scump"],
      de: ["Diesel immer günstiger", "Elektrisch: höhere Anschaffung aber -40% Betrieb, TCO ähnlich oder niedriger bei 5 Jahren", "Identisch", "Elektrisch 3x teurer"],
      en: ["Diesel always cheaper", "Electric: higher purchase but -40% operation, similar or lower TCO at 5 years", "Identical", "Electric 3x more expensive"]
    },
    correctIndex: 1,
    explanation: {
      ro: "TCO electric urban: achiziție +50%, dar energie -60%, mentenanță -40%. La 100km/zi = break-even în 3-4 ani.",
      de: "TCO elektrisch urban: Anschaffung +50%, aber Energie -60%, Wartung -40%. Bei 100km/Tag = Break-even in 3-4 Jahren.",
      en: "TCO electric urban: purchase +50%, but energy -60%, maintenance -40%. At 100km/day = break-even in 3-4 years."
    }
  },
  {
    difficultyLevel: 4,
    question: {
      ro: "Ce este well-to-wheel (WtW) în analiza emisiilor?",
      de: "Was ist Well-to-Wheel (WtW) in der Emissionsanalyse?",
      en: "What is well-to-wheel (WtW) in emission analysis?"
    },
    options: {
      ro: ["Măsurare roți", "Analiză emisii complete: de la extracție combustibil până la roată (include producție)", "Doar la pompă", "Test anvelope"],
      de: ["Radmessung", "Vollständige Emissionsanalyse: von der Kraftstoffgewinnung bis zum Rad (inkl. Produktion)", "Nur an der Zapfsäule", "Reifentest"],
      en: ["Wheel measurement", "Complete emission analysis: from fuel extraction to wheel (includes production)", "Only at pump", "Tyre test"]
    },
    correctIndex: 1,
    explanation: {
      ro: "WtW: emisii totale incluzând extracție, rafinare, transport combustibil + combustie. Mai complet decât tank-to-wheel.",
      de: "WtW: Gesamtemissionen inkl. Gewinnung, Raffination, Kraftstofftransport + Verbrennung. Vollständiger als Tank-to-Wheel.",
      en: "WtW: total emissions including extraction, refining, fuel transport + combustion. More complete than tank-to-wheel."
    }
  },
  {
    difficultyLevel: 3,
    question: {
      ro: "Ce este green logistics și ce include?",
      de: "Was ist Green Logistics und was beinhaltet sie?",
      en: "What is green logistics and what does it include?"
    },
    options: {
      ro: ["Camioane verzi", "Logistică sustenabilă: reducere emisii, optimizare rute, ambalaje eco, economie circulară", "Doar transport electric", "Marketing ecologic"],
      de: ["Grüne LKW", "Nachhaltige Logistik: Emissionsreduktion, Routenoptimierung, Öko-Verpackung, Kreislaufwirtschaft", "Nur Elektrotransport", "Öko-Marketing"],
      en: ["Green trucks", "Sustainable logistics: emission reduction, route optimization, eco packaging, circular economy", "Only electric transport", "Eco marketing"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Green logistics: reducere emisii, optimizare trasee, ambalaje sustenabile, retur ambalaje, moduri combinate.",
      de: "Green Logistics: Emissionsreduktion, Routenoptimierung, nachhaltige Verpackung, Verpackungsrücklauf, kombinierte Verkehrsträger.",
      en: "Green logistics: emission reduction, route optimization, sustainable packaging, packaging return, combined modes."
    }
  }
];
