import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ro' | 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'rossik-manual-language';

// UI Translations
const translations: Record<Language, Record<string, string>> = {
  ro: {
    // Sidebar
    'sidebar.title': 'Manual Freight Forwarding',
    'sidebar.progress': 'Progres General',
    'sidebar.chapters': 'capitole',
    'sidebar.details': 'Detalii',
    'sidebar.version': 'Versiunea 2025',
    'sidebar.edition': 'Ediție Completă',
    'sidebar.locked': 'Completează capitolul anterior cu scor ≥9/10',
    
    // Sections
    'section.foundation': 'Fundament',
    'section.equipment': 'Echipamente',
    'section.documents': 'Documente & Reglementări',
    'section.geography': 'Geografie & Rute',
    'section.commercial': 'Abilități Comerciale',
    'section.technology': 'Sisteme & Tehnologie',
    'section.finance': 'Risc & Finanțe',
    'section.practical': 'Aplicare Practică',
    
    // Chapters
    'chapter.intro': 'Introducere',
    'chapter.mindset': 'Rol & Mentalitate',
    'chapter.soft-skills': 'Soft Skills',
    'chapter.workflow': 'Flux Operațional',
    'chapter.vehicle': 'Referință Vehicule',
    'chapter.loading': 'Încărcare & Fixare',
    'chapter.reefer': 'Transport Frigorific',
    'chapter.warehouse': 'Depozit & Cross-Dock',
    'chapter.adr': 'ADR Mărfuri Periculoase',
    'chapter.documents': 'Documente Transport',
    'chapter.incoterms': 'Incoterms & Comerț',
    'chapter.compliance': 'Ore de Condus',
    'chapter.driving-time': 'Schimb vs Condus',
    'chapter.customs': 'Vamă & Frontiere',
    'chapter.europe-zones': 'Zone Europene',
    'chapter.environment': 'Mediu',
    'chapter.supply-chain': 'Lanț Aprovizionare',
    'chapter.pricing': 'Prețuri & Taxe',
    'chapter.commercial': 'Abilități Comerciale',
    'chapter.negotiation': 'Negociere',
    'chapter.clients': 'Găsirea Clienților',
    'chapter.carrier-management': 'Gestiune Transportatori',
    'chapter.exchanges': 'Burse de Marfă',
    'chapter.communication': 'Comunicare',
    'chapter.kpi': 'KPI & Performanță',
    'chapter.translogica': 'Translogica TMS',
    'chapter.fleet': 'Flotă & GPS',
    'chapter.technology': 'Tehnologie & Digital',
    'chapter.risk-management': 'Managementul Riscului',
    'chapter.insurance': 'Asigurări Transport',
    'chapter.claims': 'Daune & Dispute',
    'chapter.payment': 'Plăți & Facturare',
    'chapter.accounting': 'Contabilitate',
    'chapter.emergency': 'Proceduri Urgență',
    'chapter.case-studies': 'Studii de Caz',
    'chapter.training': 'Exerciții Training',
    'chapter.red-flags': 'Red Flags & Sfaturi',
    'chapter.glossary': 'Glosar',
    'chapter.checklists': 'Checklists',
    'chapter.licenses-oversize': 'Licențe & Agabaritic',
    'chapter.stress-management': 'Gestionare Stres',
    'chapter.sustainability': 'Sustenabilitate',
    'chapter.authorities': 'Autorități & Reglementări',
    'chapter.digitalization': 'Digitalizare',
    'chapter.european-countries': 'Țări Europene',
    'chapter.express-transport': 'Transport Express',
    'chapter.high-value-goods': 'Mărfuri de Valoare',
    'chapter.intermodal': 'Transport Intermodal',
    'chapter.networking': 'Networking',
    'chapter.professional-development': 'Dezvoltare Profesională',
    
    // Sections
    'section.advanced': 'Avansat',
    
    // Dashboard
    'dashboard.title': 'Dashboard Progres',
    'dashboard.subtitle': 'Urmărește progresul tău de învățare',
    'dashboard.back': 'Înapoi',
    'dashboard.overall': 'Progres General',
    'dashboard.completed': 'Capitole Completate',
    'dashboard.total': 'din total',
    'dashboard.quizzes': 'Teste Completate',
    'dashboard.passed': 'promovate',
    'dashboard.average': 'Scor Mediu',
    'dashboard.passRate': 'rată promovare',
    'dashboard.recent': 'Activitate Recentă',
    'dashboard.noActivity': 'Nicio activitate încă. Începe să citești capitolele!',
    'dashboard.quizPerformance': 'Performanță Teste',
    'dashboard.passRateLabel': 'Rată Promovare',
    'dashboard.totalScore': 'Scor Total',
    'dashboard.passedLabel': 'Promovate',
    'dashboard.needImprovement': 'De Îmbunătățit',
    'dashboard.allChapters': 'Toate Capitolele',
    'dashboard.congratulations': 'Felicitări!',
    'dashboard.completedAll': 'Ai completat toate capitolele și testele',
    'dashboard.reset': 'Resetează Progresul',
    'dashboard.resetConfirm': 'Ești sigur că vrei să resetezi tot progresul?',
    
    // Quiz
    'quiz.complete': 'Test Finalizat!',
    'quiz.excellent': 'Excelent! Ai stăpânit acest capitol.',
    'quiz.good': 'Bine! Revizuiește întrebările greșite.',
    'quiz.keepStudying': 'Continuă să studiezi! Revizuiește capitolul și încearcă din nou.',
    'quiz.chapterComplete': 'Capitol marcat ca finalizat!',
    'quiz.questionPool': 'Pool întrebări',
    'quiz.showing': 'Afișează',
    'quiz.perRound': 'per rundă',
    'quiz.tryAgain': 'Încearcă Din Nou',
    'quiz.newQuestions': 'Întrebări Noi',
    'quiz.question': 'Întrebarea',
    'quiz.of': 'din',
    'quiz.previousBest': 'Cel mai bun anterior',
    'quiz.correct': 'Corect!',
    'quiz.incorrect': 'Incorect',
    'quiz.next': 'Următoarea Întrebare',
    'quiz.seeResults': 'Vezi Rezultatele',
    
    // Navigation
    'nav.previous': 'Anterior',
    'nav.next': 'Următorul',
    'nav.search': 'Caută în manual...',
    'nav.noResults': 'Niciun rezultat găsit',
    
    // Language
    'language.select': 'Selectează limba',
    'language.ro': 'Română',
    'language.de': 'Deutsch',
    'language.en': 'English',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Gestionare utilizatori și progres training',
    'admin.exportCSV': 'Export CSV',
    'admin.totalUsers': 'Total Utilizatori',
    'admin.registeredUsers': 'utilizatori înregistrați',
    'admin.totalChapters': 'Capitole Total',
    'admin.availableChapters': 'capitole disponibile',
    'admin.globalAvgScore': 'Scor Mediu Global',
    'admin.allScoresAvg': 'medie toate scorurile',
    'admin.activeUsers7d': 'Utilizatori Activi (7 zile)',
    'admin.recentlyActive': 'activi recent',
    'admin.notificationsActive': 'Notificări active pentru certificate noi',
    'admin.enableNotifications': 'Activează notificările pentru certificate noi',
    
    // Admin Categories
    'admin.category.superAdmin': '🏢 SUPER ADMIN',
    'admin.category.users': '👥 UTILIZATORI',
    'admin.category.analytics': '📊 ANALIZE & KPI',
    'admin.category.competencies': '🎯 COMPETENȚE',
    'admin.category.content': '📝 CONȚINUT',
    'admin.category.system': '⚙️ SISTEM',
    
    // Admin Tabs
    'admin.tab.companies': 'Companii',
    'admin.tab.plans': 'Planuri',
    'admin.tab.premium': 'Premium',
    'admin.tab.companyUsers': 'Utilizatori Companie',
    'admin.tab.chapters': 'Capitole',
    'admin.tab.reports': 'Rapoarte',
    'admin.tab.allProfiles': 'Toate Profilurile',
    'admin.tab.retention': 'Retenție',
    'admin.tab.quizAnalytics': 'Analiză Quiz',
    'admin.tab.charts': 'Grafice',
    'admin.tab.learningKPI': 'Learning KPI',
    'admin.tab.usage': 'Utilizare',
    'admin.tab.trainingTime': 'Timp Training',
    'admin.tab.realtime': 'Timp Real',
    'admin.tab.teamCompetencies': 'Competențe Echipă',
    'admin.tab.competencyGaps': 'Lipsuri Competențe',
    'admin.tab.gamification': 'Gamificare',
    'admin.tab.certificates': 'Certificate',
    'admin.tab.contentQuality': 'Calitate Conținut',
    'admin.tab.governance': 'Guvernanță',
    'admin.tab.aiGovernor': 'AI Governor',
    'admin.tab.autoUpdate': 'Auto-Update',
    'admin.tab.intStandards': 'Standarde Int.',
    'admin.tab.knowledgeGraph': 'Knowledge Graph',
    'admin.tab.cronJobs': 'Cron Jobs',
    'admin.tab.monitoring': 'Monitorizare',
    'admin.tab.backup': 'Backup',
    'admin.tab.incidents': 'Incidente',
    'admin.tab.production': 'Production',
    
    // Admin Table
    'admin.table.user': 'Utilizator',
    'admin.table.email': 'Email',
    'admin.table.role': 'Rol',
    'admin.table.progress': 'Progres',
    'admin.table.avgScore': 'Scor Mediu',
    'admin.table.lastActivity': 'Ultima Activitate',
    'admin.table.actions': 'Acțiuni',
    'admin.table.viewDetails': 'Vezi detalii',
    
    // Admin Status
    'admin.status.completed': 'Completat',
    'admin.status.inProgress': 'În Progres',
    'admin.status.unlocked': 'Deblocat',
    'admin.status.locked': 'Blocat',
    
    // Quiz Analytics
    'admin.quiz.starts': 'Începeri Quiz',
    'admin.quiz.completions': 'Finalizări',
    'admin.quiz.refreshes': 'Refresh-uri',
    'admin.quiz.abandonRate': 'Rată Abandon',
    'admin.quiz.wrongAnswers': 'Răspunsuri Greșite',
    'admin.quiz.perChapter': 'Per Capitol',
    'admin.quiz.failedQuestions': 'Întrebări Greșite',
    'admin.quiz.perUser': 'Per Utilizator',
    'admin.quiz.refresh': 'Actualizează',
    'admin.quiz.export': 'Export CSV',
    'admin.quiz.refreshRate': 'Rată Refresh per Capitol',
    'admin.quiz.refreshRateDesc': 'Procentul de quiz-uri începute dar nefinalizate',
    'admin.quiz.completionDist': 'Distribuție Completări',
    'admin.quiz.completedVsAbandoned': 'Finalizate vs Abandonate',
    'admin.quiz.completed': 'Finalizate',
    'admin.quiz.abandoned': 'Refresh/Abandon',
    'admin.quiz.chapterDetails': 'Detalii per Capitol',
    'admin.quiz.chapter': 'Capitol',
    'admin.quiz.top30Failed': 'Top 30 Întrebări Greșite',
    'admin.quiz.mostFailed': 'Întrebările la care utilizatorii greșesc cel mai des',
    'admin.quiz.noData': 'Nu există date încă. Răspunsurile greșite vor apărea aici.',
    'admin.quiz.errors': 'greșeli',
    'admin.quiz.userStats': 'Statistici per Utilizator',
    'admin.quiz.userStatsDesc': 'Câte quiz-uri a început/finalizat fiecare utilizator',
    
    // Company Management
    'admin.company.title': 'Gestionare Companii',
    'admin.company.subtitle': 'Administrează toate companiile din platformă',
    'admin.company.new': 'Companie Nouă',
    'admin.company.create': 'Creează Companie Nouă',
    'admin.company.add': 'Adaugă o nouă companie în platformă',
    'admin.company.name': 'Nume Companie',
    'admin.company.slug': 'Slug (URL)',
    'admin.company.domain': 'Domeniu Custom (opțional)',
    'admin.company.plan': 'Plan',
    'admin.company.cancel': 'Anulează',
    'admin.company.createBtn': 'Creează',
    'admin.company.regCode': 'Cod Înregistrare',
    'admin.company.users': 'Utilizatori',
    'admin.company.status': 'Status',
    'admin.company.restricted': 'Acces restricționat',
    'admin.company.restrictedDesc': 'Doar Super Admin poate gestiona companiile.',
    'admin.company.created': 'Companie creată',
    'admin.company.createdDesc': 'a fost creată cu succes',
    'admin.company.copied': 'Copiat!',
    'admin.company.copiedDesc': 'Codul a fost copiat în clipboard',
    'admin.company.updated': 'Status actualizat',
    'admin.company.active': 'activă',
    'admin.company.inactive': 'inactivă',
    
    // Retention Dashboard
    'admin.retention.title': 'Dashboard Retenție',
    'admin.retention.activeUsers': 'Utilizatori Activi',
    'admin.retention.atRisk': 'La Risc',
    'admin.retention.inactive': 'Inactivi/Pierduți',
    'admin.retention.reEngagement': 'Rată Re-angajare',
    'admin.retention.riskDist': 'Distribuție Risc',
    'admin.retention.low': 'Scăzut',
    'admin.retention.medium': 'Mediu',
    'admin.retention.high': 'Ridicat',
    'admin.retention.critical': 'Critic',
    'admin.retention.usersAtRisk': 'Utilizatori la Risc',
    'admin.retention.messageLogs': 'Jurnal Mesaje',
    'admin.retention.runAnalysis': 'Rulează Analiză',
    'admin.retention.analyzing': 'Se analizează...',
    'admin.retention.daysInactive': 'zile inactiv',
    'admin.retention.engagement': 'Angajament',
    'admin.retention.notifications': 'notificări trimise',
    
    // Gamification
    'admin.gamification.title': 'Clasament & Gamificare',
    'admin.gamification.leaderboard': 'Clasament',
    'admin.gamification.achievements': 'Realizări',
    'admin.gamification.simStats': 'Statistici Simulări',
    'admin.gamification.activeUsers': 'Utilizatori Activi',
    'admin.gamification.simCompleted': 'Simulări Finalizate',
    'admin.gamification.avgScore': 'Scor Mediu',
    'admin.gamification.totalXP': 'XP Total',
    'admin.gamification.level': 'Nivel',
    'admin.gamification.simulations': 'Simulări',
    'admin.gamification.streak': 'Serie Zile',
    'admin.gamification.topPerformers': 'Top Performeri Simulări',
    'admin.gamification.simPopularity': 'Popularitate Simulări',
    
    // General Admin
    'admin.general.loading': 'Se încarcă...',
    'admin.general.error': 'Eroare',
    'admin.general.save': 'Salvează',
    'admin.general.delete': 'Șterge',
    'admin.general.edit': 'Editează',
    'admin.general.view': 'Vezi',
    'admin.general.close': 'Închide',
    'admin.general.confirm': 'Confirmă',
    'admin.general.noData': 'Nu există date',
    'admin.general.perMonth': '/lună',
  },
  de: {
    // Sidebar
    'sidebar.title': 'Speditionshandbuch',
    'sidebar.progress': 'Gesamtfortschritt',
    'sidebar.chapters': 'Kapitel',
    'sidebar.details': 'Details',
    'sidebar.version': 'Version 2025',
    'sidebar.edition': 'Vollständige Ausgabe',
    'sidebar.locked': 'Schließen Sie das vorherige Kapitel mit ≥9/10 ab',
    
    // Sections
    'section.foundation': 'Grundlagen',
    'section.equipment': 'Ausrüstung',
    'section.documents': 'Dokumente & Vorschriften',
    'section.geography': 'Geographie & Routen',
    'section.commercial': 'Kaufmännische Fähigkeiten',
    'section.technology': 'Systeme & Technologie',
    'section.finance': 'Risiko & Finanzen',
    'section.practical': 'Praktische Anwendung',
    
    // Chapters
    'chapter.intro': 'Einführung',
    'chapter.mindset': 'Rolle & Denkweise',
    'chapter.soft-skills': 'Soft Skills',
    'chapter.workflow': 'Betriebsablauf',
    'chapter.vehicle': 'Fahrzeugreferenz',
    'chapter.loading': 'Laden & Sichern',
    'chapter.reefer': 'Kühltransport',
    'chapter.warehouse': 'Lager & Cross-Dock',
    'chapter.adr': 'ADR Gefahrgut',
    'chapter.documents': 'Transportdokumente',
    'chapter.incoterms': 'Incoterms & Handel',
    'chapter.compliance': 'Lenkzeiten',
    'chapter.driving-time': 'Schicht vs Fahren',
    'chapter.customs': 'Zoll & Grenzen',
    'chapter.europe-zones': 'Europäische Zonen',
    'chapter.environment': 'Umwelt',
    'chapter.supply-chain': 'Lieferkette',
    'chapter.pricing': 'Preise & Gebühren',
    'chapter.commercial': 'Kaufmännische Fähigkeiten',
    'chapter.negotiation': 'Verhandlung',
    'chapter.clients': 'Kundenakquise',
    'chapter.carrier-management': 'Frachtführerverwaltung',
    'chapter.exchanges': 'Frachtbörsen',
    'chapter.communication': 'Kommunikation',
    'chapter.kpi': 'KPI & Leistung',
    'chapter.translogica': 'Translogica TMS',
    'chapter.fleet': 'Flotte & GPS',
    'chapter.technology': 'Technologie & Digital',
    'chapter.risk-management': 'Risikomanagement',
    'chapter.insurance': 'Transportversicherung',
    'chapter.claims': 'Schäden & Streitigkeiten',
    'chapter.payment': 'Zahlung & Rechnungsstellung',
    'chapter.accounting': 'Buchhaltung',
    'chapter.emergency': 'Notfallverfahren',
    'chapter.case-studies': 'Fallstudien',
    'chapter.training': 'Trainingsübungen',
    'chapter.red-flags': 'Warnzeichen & Tipps',
    'chapter.glossary': 'Glossar',
    'chapter.checklists': 'Checklisten',
    'chapter.licenses-oversize': 'Lizenzen & Schwertransport',
    'chapter.stress-management': 'Stressmanagement',
    'chapter.sustainability': 'Nachhaltigkeit',
    'chapter.authorities': 'Behörden & Vorschriften',
    'chapter.digitalization': 'Digitalisierung',
    'chapter.european-countries': 'Europäische Länder',
    'chapter.express-transport': 'Expresstransport',
    'chapter.high-value-goods': 'Wertgüter',
    'chapter.intermodal': 'Intermodaler Transport',
    'chapter.networking': 'Networking',
    'chapter.professional-development': 'Berufliche Entwicklung',
    
    // Sections
    'section.advanced': 'Fortgeschritten',
    
    // Dashboard
    'dashboard.title': 'Fortschritts-Dashboard',
    'dashboard.subtitle': 'Verfolgen Sie Ihren Lernfortschritt',
    'dashboard.back': 'Zurück',
    'dashboard.overall': 'Gesamtfortschritt',
    'dashboard.completed': 'Abgeschlossene Kapitel',
    'dashboard.total': 'von insgesamt',
    'dashboard.quizzes': 'Abgeschlossene Tests',
    'dashboard.passed': 'bestanden',
    'dashboard.average': 'Durchschnittsnote',
    'dashboard.passRate': 'Erfolgsquote',
    'dashboard.recent': 'Letzte Aktivität',
    'dashboard.noActivity': 'Noch keine Aktivität. Beginnen Sie mit dem Lesen!',
    'dashboard.quizPerformance': 'Testleistung',
    'dashboard.passRateLabel': 'Erfolgsquote',
    'dashboard.totalScore': 'Gesamtpunktzahl',
    'dashboard.passedLabel': 'Bestanden',
    'dashboard.needImprovement': 'Verbesserungsbedarf',
    'dashboard.allChapters': 'Alle Kapitel',
    'dashboard.congratulations': 'Herzlichen Glückwunsch!',
    'dashboard.completedAll': 'Sie haben alle Kapitel und Tests abgeschlossen',
    'dashboard.reset': 'Fortschritt zurücksetzen',
    'dashboard.resetConfirm': 'Sind Sie sicher, dass Sie den gesamten Fortschritt zurücksetzen möchten?',
    
    // Quiz
    'quiz.complete': 'Test Abgeschlossen!',
    'quiz.excellent': 'Ausgezeichnet! Sie beherrschen dieses Kapitel.',
    'quiz.good': 'Gut! Überprüfen Sie die falschen Fragen.',
    'quiz.keepStudying': 'Weiter lernen! Kapitel erneut lesen und noch einmal versuchen.',
    'quiz.chapterComplete': 'Kapitel als abgeschlossen markiert!',
    'quiz.questionPool': 'Fragenpool',
    'quiz.showing': 'Anzeigen',
    'quiz.perRound': 'pro Runde',
    'quiz.tryAgain': 'Erneut Versuchen',
    'quiz.newQuestions': 'Neue Fragen',
    'quiz.question': 'Frage',
    'quiz.of': 'von',
    'quiz.previousBest': 'Bisherige Bestleistung',
    'quiz.correct': 'Richtig!',
    'quiz.incorrect': 'Falsch',
    'quiz.next': 'Nächste Frage',
    'quiz.seeResults': 'Ergebnisse Anzeigen',
    
    // Navigation
    'nav.previous': 'Vorherige',
    'nav.next': 'Nächste',
    'nav.search': 'Im Handbuch suchen...',
    'nav.noResults': 'Keine Ergebnisse gefunden',
    
    // Language
    'language.select': 'Sprache wählen',
    'language.ro': 'Română',
    'language.de': 'Deutsch',
    'language.en': 'English',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Benutzer- und Schulungsfortschritt verwalten',
    'admin.exportCSV': 'CSV exportieren',
    'admin.totalUsers': 'Benutzer Gesamt',
    'admin.registeredUsers': 'registrierte Benutzer',
    'admin.totalChapters': 'Kapitel Gesamt',
    'admin.availableChapters': 'verfügbare Kapitel',
    'admin.globalAvgScore': 'Globaler Durchschnitt',
    'admin.allScoresAvg': 'Durchschnitt aller Punkte',
    'admin.activeUsers7d': 'Aktive Benutzer (7 Tage)',
    'admin.recentlyActive': 'kürzlich aktiv',
    'admin.notificationsActive': 'Benachrichtigungen für neue Zertifikate aktiv',
    'admin.enableNotifications': 'Benachrichtigungen für neue Zertifikate aktivieren',
    
    // Admin Categories
    'admin.category.superAdmin': '🏢 SUPER ADMIN',
    'admin.category.users': '👥 BENUTZER',
    'admin.category.analytics': '📊 ANALYSEN & KPI',
    'admin.category.competencies': '🎯 KOMPETENZEN',
    'admin.category.content': '📝 INHALT',
    'admin.category.system': '⚙️ SYSTEM',
    
    // Admin Tabs
    'admin.tab.companies': 'Unternehmen',
    'admin.tab.plans': 'Pläne',
    'admin.tab.premium': 'Premium',
    'admin.tab.companyUsers': 'Unternehmensbenutzer',
    'admin.tab.chapters': 'Kapitel',
    'admin.tab.reports': 'Berichte',
    'admin.tab.allProfiles': 'Alle Profile',
    'admin.tab.retention': 'Bindung',
    'admin.tab.quizAnalytics': 'Quiz-Analyse',
    'admin.tab.charts': 'Diagramme',
    'admin.tab.learningKPI': 'Lern-KPI',
    'admin.tab.usage': 'Nutzung',
    'admin.tab.trainingTime': 'Trainingszeit',
    'admin.tab.realtime': 'Echtzeit',
    'admin.tab.teamCompetencies': 'Team-Kompetenzen',
    'admin.tab.competencyGaps': 'Kompetenzlücken',
    'admin.tab.gamification': 'Gamification',
    'admin.tab.certificates': 'Zertifikate',
    'admin.tab.contentQuality': 'Inhaltsqualität',
    'admin.tab.governance': 'Governance',
    'admin.tab.aiGovernor': 'AI Governor',
    'admin.tab.autoUpdate': 'Auto-Update',
    'admin.tab.intStandards': 'Int. Standards',
    'admin.tab.knowledgeGraph': 'Wissensgraph',
    'admin.tab.cronJobs': 'Cron Jobs',
    'admin.tab.monitoring': 'Überwachung',
    'admin.tab.backup': 'Backup',
    'admin.tab.incidents': 'Vorfälle',
    'admin.tab.production': 'Produktion',
    
    // Admin Table
    'admin.table.user': 'Benutzer',
    'admin.table.email': 'E-Mail',
    'admin.table.role': 'Rolle',
    'admin.table.progress': 'Fortschritt',
    'admin.table.avgScore': 'Durchschnitt',
    'admin.table.lastActivity': 'Letzte Aktivität',
    'admin.table.actions': 'Aktionen',
    'admin.table.viewDetails': 'Details anzeigen',
    
    // Admin Status
    'admin.status.completed': 'Abgeschlossen',
    'admin.status.inProgress': 'In Bearbeitung',
    'admin.status.unlocked': 'Freigeschaltet',
    'admin.status.locked': 'Gesperrt',
    
    // Quiz Analytics
    'admin.quiz.starts': 'Quiz-Starts',
    'admin.quiz.completions': 'Abschlüsse',
    'admin.quiz.refreshes': 'Aktualisierungen',
    'admin.quiz.abandonRate': 'Abbruchrate',
    'admin.quiz.wrongAnswers': 'Falsche Antworten',
    'admin.quiz.perChapter': 'Pro Kapitel',
    'admin.quiz.failedQuestions': 'Fehlgeschlagene Fragen',
    'admin.quiz.perUser': 'Pro Benutzer',
    'admin.quiz.refresh': 'Aktualisieren',
    'admin.quiz.export': 'CSV Exportieren',
    'admin.quiz.refreshRate': 'Aktualisierungsrate pro Kapitel',
    'admin.quiz.refreshRateDesc': 'Prozentsatz der gestarteten aber nicht abgeschlossenen Quiz',
    'admin.quiz.completionDist': 'Abschlussverteilung',
    'admin.quiz.completedVsAbandoned': 'Abgeschlossen vs Abgebrochen',
    'admin.quiz.completed': 'Abgeschlossen',
    'admin.quiz.abandoned': 'Aktualisierung/Abbruch',
    'admin.quiz.chapterDetails': 'Details pro Kapitel',
    'admin.quiz.chapter': 'Kapitel',
    'admin.quiz.top30Failed': 'Top 30 Fehlgeschlagene Fragen',
    'admin.quiz.mostFailed': 'Fragen, bei denen Benutzer am häufigsten Fehler machen',
    'admin.quiz.noData': 'Noch keine Daten. Falsche Antworten werden hier angezeigt.',
    'admin.quiz.errors': 'Fehler',
    'admin.quiz.userStats': 'Statistiken pro Benutzer',
    'admin.quiz.userStatsDesc': 'Wie viele Quiz jeder Benutzer gestartet/abgeschlossen hat',
    
    // Company Management
    'admin.company.title': 'Unternehmensverwaltung',
    'admin.company.subtitle': 'Verwalten Sie alle Unternehmen der Plattform',
    'admin.company.new': 'Neues Unternehmen',
    'admin.company.create': 'Neues Unternehmen Erstellen',
    'admin.company.add': 'Neues Unternehmen zur Plattform hinzufügen',
    'admin.company.name': 'Unternehmensname',
    'admin.company.slug': 'Slug (URL)',
    'admin.company.domain': 'Benutzerdefinierte Domain (optional)',
    'admin.company.plan': 'Plan',
    'admin.company.cancel': 'Abbrechen',
    'admin.company.createBtn': 'Erstellen',
    'admin.company.regCode': 'Registrierungscode',
    'admin.company.users': 'Benutzer',
    'admin.company.status': 'Status',
    'admin.company.restricted': 'Zugang eingeschränkt',
    'admin.company.restrictedDesc': 'Nur Super Admin kann Unternehmen verwalten.',
    'admin.company.created': 'Unternehmen erstellt',
    'admin.company.createdDesc': 'wurde erfolgreich erstellt',
    'admin.company.copied': 'Kopiert!',
    'admin.company.copiedDesc': 'Code in Zwischenablage kopiert',
    'admin.company.updated': 'Status aktualisiert',
    'admin.company.active': 'aktiv',
    'admin.company.inactive': 'inaktiv',
    
    // Retention Dashboard
    'admin.retention.title': 'Bindungs-Dashboard',
    'admin.retention.activeUsers': 'Aktive Benutzer',
    'admin.retention.atRisk': 'Gefährdet',
    'admin.retention.inactive': 'Inaktiv/Verloren',
    'admin.retention.reEngagement': 'Wiederbindungsrate',
    'admin.retention.riskDist': 'Risikoverteilung',
    'admin.retention.low': 'Niedrig',
    'admin.retention.medium': 'Mittel',
    'admin.retention.high': 'Hoch',
    'admin.retention.critical': 'Kritisch',
    'admin.retention.usersAtRisk': 'Gefährdete Benutzer',
    'admin.retention.messageLogs': 'Nachrichtenprotokoll',
    'admin.retention.runAnalysis': 'Analyse Starten',
    'admin.retention.analyzing': 'Analysiere...',
    'admin.retention.daysInactive': 'Tage inaktiv',
    'admin.retention.engagement': 'Engagement',
    'admin.retention.notifications': 'Benachrichtigungen gesendet',
    
    // Gamification
    'admin.gamification.title': 'Bestenliste & Gamification',
    'admin.gamification.leaderboard': 'Bestenliste',
    'admin.gamification.achievements': 'Erfolge',
    'admin.gamification.simStats': 'Simulationsstatistiken',
    'admin.gamification.activeUsers': 'Aktive Benutzer',
    'admin.gamification.simCompleted': 'Simulationen Abgeschlossen',
    'admin.gamification.avgScore': 'Durchschnittsnote',
    'admin.gamification.totalXP': 'Gesamt XP',
    'admin.gamification.level': 'Stufe',
    'admin.gamification.simulations': 'Simulationen',
    'admin.gamification.streak': 'Tagessträhne',
    'admin.gamification.topPerformers': 'Top Simulationsperformer',
    'admin.gamification.simPopularity': 'Simulationsbeliebtheit',
    
    // General Admin
    'admin.general.loading': 'Laden...',
    'admin.general.error': 'Fehler',
    'admin.general.save': 'Speichern',
    'admin.general.delete': 'Löschen',
    'admin.general.edit': 'Bearbeiten',
    'admin.general.view': 'Anzeigen',
    'admin.general.close': 'Schließen',
    'admin.general.confirm': 'Bestätigen',
    'admin.general.noData': 'Keine Daten vorhanden',
    'admin.general.perMonth': '/Monat',
  },
  en: {
    // Sidebar
    'sidebar.title': 'Freight Forwarding Manual',
    'sidebar.progress': 'Overall Progress',
    'sidebar.chapters': 'chapters',
    'sidebar.details': 'Details',
    'sidebar.version': 'Version 2025',
    'sidebar.edition': 'Complete Edition',
    'sidebar.locked': 'Complete the previous chapter with score ≥9/10',
    
    // Sections
    'section.foundation': 'Foundation',
    'section.equipment': 'Equipment & Handling',
    'section.documents': 'Documents & Regulations',
    'section.geography': 'Geography & Routes',
    'section.commercial': 'Commercial Skills',
    'section.technology': 'Systems & Technology',
    'section.finance': 'Risk & Finance',
    'section.practical': 'Practical Application',
    
    // Chapters
    'chapter.intro': 'Introduction',
    'chapter.mindset': 'Role & Mindset',
    'chapter.soft-skills': 'Soft Skills',
    'chapter.workflow': 'Operational Workflow',
    'chapter.vehicle': 'Vehicle Reference',
    'chapter.loading': 'Loading & Securing',
    'chapter.reefer': 'Temperature Transport',
    'chapter.warehouse': 'Warehouse & Cross-Dock',
    'chapter.adr': 'ADR Dangerous Goods',
    'chapter.documents': 'Transport Documents',
    'chapter.incoterms': 'Incoterms & Trade',
    'chapter.compliance': 'Driving Hours',
    'chapter.driving-time': 'Shift vs Driving',
    'chapter.customs': 'Customs & Borders',
    'chapter.europe-zones': 'European Zones',
    'chapter.environment': 'Environmental',
    'chapter.supply-chain': 'Supply Chain',
    'chapter.pricing': 'Pricing & Tolls',
    'chapter.commercial': 'Commercial Skills',
    'chapter.negotiation': 'Negotiation',
    'chapter.clients': 'Finding Clients',
    'chapter.carrier-management': 'Carrier Management',
    'chapter.exchanges': 'Freight Exchanges',
    'chapter.communication': 'Communication',
    'chapter.kpi': 'KPIs & Performance',
    'chapter.translogica': 'Translogica TMS',
    'chapter.fleet': 'Fleet & GPS',
    'chapter.technology': 'Technology & Digital',
    'chapter.risk-management': 'Risk Management',
    'chapter.insurance': 'Transport Insurance',
    'chapter.claims': 'Claims & Disputes',
    'chapter.payment': 'Payment & Invoicing',
    'chapter.accounting': 'Accounting & Finance',
    'chapter.emergency': 'Emergency Procedures',
    'chapter.case-studies': 'Case Studies',
    'chapter.training': 'Training Exercises',
    'chapter.red-flags': 'Red Flags & Tips',
    'chapter.glossary': 'Glossary',
    'chapter.checklists': 'Checklists',
    'chapter.licenses-oversize': 'Licenses & Oversize',
    'chapter.stress-management': 'Stress Management',
    'chapter.sustainability': 'Sustainability',
    'chapter.authorities': 'Authorities & Regulations',
    'chapter.digitalization': 'Digitalization',
    'chapter.european-countries': 'European Countries',
    'chapter.express-transport': 'Express Transport',
    'chapter.high-value-goods': 'High-Value Goods',
    'chapter.intermodal': 'Intermodal Transport',
    'chapter.networking': 'Networking',
    'chapter.professional-development': 'Professional Development',
    
    // Sections
    'section.advanced': 'Advanced',
    
    // Dashboard
    'dashboard.title': 'Progress Dashboard',
    'dashboard.subtitle': 'Track your learning journey',
    'dashboard.back': 'Back',
    'dashboard.overall': 'Overall Progress',
    'dashboard.completed': 'Chapters Completed',
    'dashboard.total': 'of total',
    'dashboard.quizzes': 'Quizzes Completed',
    'dashboard.passed': 'passed',
    'dashboard.average': 'Average Score',
    'dashboard.passRate': 'pass rate',
    'dashboard.recent': 'Recent Activity',
    'dashboard.noActivity': 'No activity yet. Start reading chapters!',
    'dashboard.quizPerformance': 'Quiz Performance',
    'dashboard.passRateLabel': 'Pass Rate',
    'dashboard.totalScore': 'Total Score',
    'dashboard.passedLabel': 'Passed',
    'dashboard.needImprovement': 'Need Improvement',
    'dashboard.allChapters': 'All Chapters',
    'dashboard.congratulations': 'Congratulations!',
    'dashboard.completedAll': 'You have completed all chapters and quizzes',
    'dashboard.reset': 'Reset Progress',
    'dashboard.resetConfirm': 'Are you sure you want to reset all progress?',
    
    // Quiz
    'quiz.complete': 'Quiz Complete!',
    'quiz.excellent': 'Excellent work! You\'ve mastered this chapter.',
    'quiz.good': 'Good job! Review the missed questions.',
    'quiz.keepStudying': 'Keep studying! Review the chapter and try again.',
    'quiz.chapterComplete': 'Chapter marked as complete!',
    'quiz.questionPool': 'Question pool',
    'quiz.showing': 'Showing',
    'quiz.perRound': 'per round',
    'quiz.tryAgain': 'Try Again',
    'quiz.newQuestions': 'New Questions',
    'quiz.question': 'Question',
    'quiz.of': 'of',
    'quiz.previousBest': 'Previous best',
    'quiz.correct': 'Correct!',
    'quiz.incorrect': 'Incorrect',
    'quiz.next': 'Next Question',
    'quiz.seeResults': 'See Results',
    
    // Navigation
    'nav.previous': 'Previous',
    'nav.next': 'Next',
    'nav.search': 'Search manual...',
    'nav.noResults': 'No results found',
    
    // Language
    'language.select': 'Select language',
    'language.ro': 'Română',
    'language.de': 'Deutsch',
    'language.en': 'English',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage users and training progress',
    'admin.exportCSV': 'Export CSV',
    'admin.totalUsers': 'Total Users',
    'admin.registeredUsers': 'registered users',
    'admin.totalChapters': 'Total Chapters',
    'admin.availableChapters': 'available chapters',
    'admin.globalAvgScore': 'Global Average Score',
    'admin.allScoresAvg': 'average of all scores',
    'admin.activeUsers7d': 'Active Users (7 days)',
    'admin.recentlyActive': 'recently active',
    'admin.notificationsActive': 'Notifications active for new certificates',
    'admin.enableNotifications': 'Enable notifications for new certificates',
    
    // Admin Categories
    'admin.category.superAdmin': '🏢 SUPER ADMIN',
    'admin.category.users': '👥 USERS',
    'admin.category.analytics': '📊 ANALYTICS & KPI',
    'admin.category.competencies': '🎯 COMPETENCIES',
    'admin.category.content': '📝 CONTENT',
    'admin.category.system': '⚙️ SYSTEM',
    
    // Admin Tabs
    'admin.tab.companies': 'Companies',
    'admin.tab.plans': 'Plans',
    'admin.tab.premium': 'Premium',
    'admin.tab.companyUsers': 'Company Users',
    'admin.tab.chapters': 'Chapters',
    'admin.tab.reports': 'Reports',
    'admin.tab.allProfiles': 'All Profiles',
    'admin.tab.retention': 'Retention',
    'admin.tab.quizAnalytics': 'Quiz Analytics',
    'admin.tab.charts': 'Charts',
    'admin.tab.learningKPI': 'Learning KPI',
    'admin.tab.usage': 'Usage',
    'admin.tab.trainingTime': 'Training Time',
    'admin.tab.realtime': 'Real-time',
    'admin.tab.teamCompetencies': 'Team Competencies',
    'admin.tab.competencyGaps': 'Competency Gaps',
    'admin.tab.gamification': 'Gamification',
    'admin.tab.certificates': 'Certificates',
    'admin.tab.contentQuality': 'Content Quality',
    'admin.tab.governance': 'Governance',
    'admin.tab.aiGovernor': 'AI Governor',
    'admin.tab.autoUpdate': 'Auto-Update',
    'admin.tab.intStandards': 'Int. Standards',
    'admin.tab.knowledgeGraph': 'Knowledge Graph',
    'admin.tab.cronJobs': 'Cron Jobs',
    'admin.tab.monitoring': 'Monitoring',
    'admin.tab.backup': 'Backup',
    'admin.tab.incidents': 'Incidents',
    'admin.tab.production': 'Production',
    
    // Admin Table
    'admin.table.user': 'User',
    'admin.table.email': 'Email',
    'admin.table.role': 'Role',
    'admin.table.progress': 'Progress',
    'admin.table.avgScore': 'Avg Score',
    'admin.table.lastActivity': 'Last Activity',
    'admin.table.actions': 'Actions',
    'admin.table.viewDetails': 'View details',
    
    // Admin Status
    'admin.status.completed': 'Completed',
    'admin.status.inProgress': 'In Progress',
    'admin.status.unlocked': 'Unlocked',
    'admin.status.locked': 'Locked',
    
    // Quiz Analytics
    'admin.quiz.starts': 'Quiz Starts',
    'admin.quiz.completions': 'Completions',
    'admin.quiz.refreshes': 'Refreshes',
    'admin.quiz.abandonRate': 'Abandon Rate',
    'admin.quiz.wrongAnswers': 'Wrong Answers',
    'admin.quiz.perChapter': 'Per Chapter',
    'admin.quiz.failedQuestions': 'Failed Questions',
    'admin.quiz.perUser': 'Per User',
    'admin.quiz.refresh': 'Refresh',
    'admin.quiz.export': 'Export CSV',
    'admin.quiz.refreshRate': 'Refresh Rate per Chapter',
    'admin.quiz.refreshRateDesc': 'Percentage of quizzes started but not completed',
    'admin.quiz.completionDist': 'Completion Distribution',
    'admin.quiz.completedVsAbandoned': 'Completed vs Abandoned',
    'admin.quiz.completed': 'Completed',
    'admin.quiz.abandoned': 'Refresh/Abandon',
    'admin.quiz.chapterDetails': 'Chapter Details',
    'admin.quiz.chapter': 'Chapter',
    'admin.quiz.top30Failed': 'Top 30 Failed Questions',
    'admin.quiz.mostFailed': 'Questions users fail most often',
    'admin.quiz.noData': 'No data yet. Wrong answers will appear here.',
    'admin.quiz.errors': 'errors',
    'admin.quiz.userStats': 'User Statistics',
    'admin.quiz.userStatsDesc': 'How many quizzes each user has started/completed',
    
    // Company Management
    'admin.company.title': 'Company Management',
    'admin.company.subtitle': 'Manage all companies in the platform',
    'admin.company.new': 'New Company',
    'admin.company.create': 'Create New Company',
    'admin.company.add': 'Add a new company to the platform',
    'admin.company.name': 'Company Name',
    'admin.company.slug': 'Slug (URL)',
    'admin.company.domain': 'Custom Domain (optional)',
    'admin.company.plan': 'Plan',
    'admin.company.cancel': 'Cancel',
    'admin.company.createBtn': 'Create',
    'admin.company.regCode': 'Registration Code',
    'admin.company.users': 'Users',
    'admin.company.status': 'Status',
    'admin.company.restricted': 'Access Restricted',
    'admin.company.restrictedDesc': 'Only Super Admin can manage companies.',
    'admin.company.created': 'Company created',
    'admin.company.createdDesc': 'was created successfully',
    'admin.company.copied': 'Copied!',
    'admin.company.copiedDesc': 'Code copied to clipboard',
    'admin.company.updated': 'Status updated',
    'admin.company.active': 'active',
    'admin.company.inactive': 'inactive',
    
    // Retention Dashboard
    'admin.retention.title': 'Retention Dashboard',
    'admin.retention.activeUsers': 'Active Users',
    'admin.retention.atRisk': 'At Risk',
    'admin.retention.inactive': 'Inactive/Churned',
    'admin.retention.reEngagement': 'Re-engagement Rate',
    'admin.retention.riskDist': 'Risk Distribution',
    'admin.retention.low': 'Low',
    'admin.retention.medium': 'Medium',
    'admin.retention.high': 'High',
    'admin.retention.critical': 'Critical',
    'admin.retention.usersAtRisk': 'Users at Risk',
    'admin.retention.messageLogs': 'Message Logs',
    'admin.retention.runAnalysis': 'Run Analysis',
    'admin.retention.analyzing': 'Analyzing...',
    'admin.retention.daysInactive': 'days inactive',
    'admin.retention.engagement': 'Engagement',
    'admin.retention.notifications': 'notifications sent',
    
    // Gamification
    'admin.gamification.title': 'Leaderboard & Gamification',
    'admin.gamification.leaderboard': 'Leaderboard',
    'admin.gamification.achievements': 'Achievements',
    'admin.gamification.simStats': 'Simulation Statistics',
    'admin.gamification.activeUsers': 'Active Users',
    'admin.gamification.simCompleted': 'Simulations Completed',
    'admin.gamification.avgScore': 'Average Score',
    'admin.gamification.totalXP': 'Total XP',
    'admin.gamification.level': 'Level',
    'admin.gamification.simulations': 'Simulations',
    'admin.gamification.streak': 'Day Streak',
    'admin.gamification.topPerformers': 'Top Simulation Performers',
    'admin.gamification.simPopularity': 'Simulation Popularity',
    
    // General Admin
    'admin.general.loading': 'Loading...',
    'admin.general.error': 'Error',
    'admin.general.save': 'Save',
    'admin.general.delete': 'Delete',
    'admin.general.edit': 'Edit',
    'admin.general.view': 'View',
    'admin.general.close': 'Close',
    'admin.general.confirm': 'Confirm',
    'admin.general.noData': 'No data available',
    'admin.general.perMonth': '/month',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('ro');

  useEffect(() => {
    const stored = localStorage.getItem(STORAGE_KEY) as Language | null;
    if (stored && ['ro', 'de', 'en'].includes(stored)) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(STORAGE_KEY, lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { translations };
