import { Language } from '@/contexts/LanguageContext';

interface QuizQuestion {
  question: Record<Language, string>;
  options: Record<Language, string[]>;
  correctIndex: number;
  explanation: Record<Language, string>;
}

export const environmentQuestions: QuizQuestion[] = [
  {
    question: {
      ro: "Ce reprezintă Euro 6 pentru vehicule de transport?",
      de: "Was bedeutet Euro 6 für Transportfahrzeuge?",
      en: "What does Euro 6 represent for transport vehicles?"
    },
    options: {
      ro: ["Preț în euro", "Standard de emisii pentru camioane noi", "Taxă de drum", "Clasă de greutate"],
      de: ["Preis in Euro", "Emissionsstandard für neue LKW", "Straßengebühr", "Gewichtsklasse"],
      en: ["Price in euros", "Emission standard for new trucks", "Road tax", "Weight class"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Euro 6 este cel mai strict standard UE pentru emisiile de NOx și particule.",
      de: "Euro 6 ist der strengste EU-Standard für NOx- und Partikelemissionen.",
      en: "Euro 6 is the strictest EU standard for NOx and particle emissions."
    }
  },
  {
    question: {
      ro: "Ce este amprenta de carbon în transport?",
      de: "Was ist der CO2-Fußabdruck im Transport?",
      en: "What is carbon footprint in transport?"
    },
    options: {
      ro: ["Urmă de cauciuc", "Totalul emisiilor de CO2 generate de activitatea de transport", "Distanța parcursă", "Greutatea mărfii"],
      de: ["Reifenspur", "Gesamte CO2-Emissionen der Transportaktivität", "Zurückgelegte Strecke", "Frachtgewicht"],
      en: ["Tire track", "Total CO2 emissions generated by transport activity", "Distance traveled", "Cargo weight"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Amprenta de carbon măsoară impactul asupra mediului și devine cerință pentru mulți clienți.",
      de: "Der CO2-Fußabdruck misst Umweltauswirkungen und wird für viele Kunden zur Anforderung.",
      en: "Carbon footprint measures environmental impact and is becoming a requirement for many clients."
    }
  },
  {
    question: {
      ro: "Ce este economia circulară în logistică?",
      de: "Was ist Kreislaufwirtschaft in der Logistik?",
      en: "What is circular economy in logistics?"
    },
    options: {
      ro: ["Transport în cerc", "Sistem de reutilizare, reciclare și minimizare a deșeurilor", "Livrări circulare", "Depozite rotunde"],
      de: ["Transport im Kreis", "System der Wiederverwendung, Recycling und Abfallminimierung", "Kreisförmige Lieferungen", "Runde Lager"],
      en: ["Transport in circle", "System of reuse, recycling and waste minimization", "Circular deliveries", "Round warehouses"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Economia circulară optimizează utilizarea resurselor și reduce impactul de mediu.",
      de: "Kreislaufwirtschaft optimiert Ressourcennutzung und reduziert Umweltauswirkungen.",
      en: "Circular economy optimizes resource use and reduces environmental impact."
    }
  },
  {
    question: {
      ro: "Ce sunt zonele cu emisii zero (ZEZ)?",
      de: "Was sind Null-Emissions-Zonen (ZEZ)?",
      en: "What are Zero Emission Zones (ZEZ)?"
    },
    options: {
      ro: ["Zone gratuite", "Arii urbane care permit doar vehicule fără emisii la țeava de eșapament", "Zone industriale", "Zone comerciale"],
      de: ["Kostenlose Zonen", "Städtische Gebiete die nur Fahrzeuge ohne Auspuffemissionen erlauben", "Industriezonen", "Gewerbezonen"],
      en: ["Free zones", "Urban areas allowing only vehicles without exhaust emissions", "Industrial zones", "Commercial zones"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ZEZ vor deveni mai frecvente în marile orașe europene.",
      de: "ZEZ werden in großen europäischen Städten häufiger werden.",
      en: "ZEZ will become more common in major European cities."
    }
  },
  {
    question: {
      ro: "Ce combustibili alternativi există pentru camioane?",
      de: "Welche alternativen Kraftstoffe gibt es für LKW?",
      en: "What alternative fuels exist for trucks?"
    },
    options: {
      ro: ["Doar diesel", "LNG, CNG, HVO, electric, hidrogen", "Doar benzină", "Doar apă"],
      de: ["Nur Diesel", "LNG, CNG, HVO, elektrisch, Wasserstoff", "Nur Benzin", "Nur Wasser"],
      en: ["Only diesel", "LNG, CNG, HVO, electric, hydrogen", "Only petrol", "Only water"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Alternativele la diesel reduc emisiile și vor deveni obligatorii în viitor.",
      de: "Alternativen zu Diesel reduzieren Emissionen und werden in Zukunft obligatorisch.",
      en: "Alternatives to diesel reduce emissions and will become mandatory in the future."
    }
  },
  {
    question: {
      ro: "Ce este HVO (Hydrotreated Vegetable Oil)?",
      de: "Was ist HVO (Hydrotreated Vegetable Oil)?",
      en: "What is HVO (Hydrotreated Vegetable Oil)?"
    },
    options: {
      ro: ["Ulei de gătit", "Biodiesel de înaltă calitate compatibil cu motoarele diesel existente", "Lubrifiant", "Combustibil sintetic"],
      de: ["Speiseöl", "Hochwertiger Biodiesel kompatibel mit bestehenden Dieselmotoren", "Schmiermittel", "Synthetischer Kraftstoff"],
      en: ["Cooking oil", "High-quality biodiesel compatible with existing diesel engines", "Lubricant", "Synthetic fuel"]
    },
    correctIndex: 1,
    explanation: {
      ro: "HVO poate reduce emisiile de CO2 cu până la 90% față de dieselul convențional.",
      de: "HVO kann CO2-Emissionen um bis zu 90% gegenüber konventionellem Diesel reduzieren.",
      en: "HVO can reduce CO2 emissions by up to 90% compared to conventional diesel."
    }
  },
  {
    question: {
      ro: "Ce este eco-driving?",
      de: "Was ist Eco-Driving?",
      en: "What is eco-driving?"
    },
    options: {
      ro: ["Conducere rapidă", "Tehnică de conducere eficientă care reduce consumul și emisiile", "Conducere pe autostrăzi", "Conducere nocturnă"],
      de: ["Schnelles Fahren", "Effiziente Fahrtechnik die Verbrauch und Emissionen reduziert", "Autobahnfahren", "Nachtfahren"],
      en: ["Fast driving", "Efficient driving technique reducing consumption and emissions", "Highway driving", "Night driving"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Eco-driving poate reduce consumul cu 10-15% prin tehnici corecte.",
      de: "Eco-Driving kann den Verbrauch durch richtige Techniken um 10-15% reduzieren.",
      en: "Eco-driving can reduce consumption by 10-15% through proper techniques."
    }
  },
  {
    question: {
      ro: "Ce reprezintă certificarea ISO 14001?",
      de: "Was bedeutet die ISO 14001-Zertifizierung?",
      en: "What does ISO 14001 certification represent?"
    },
    options: {
      ro: ["Standard de calitate", "Standard internațional de management de mediu", "Standard de siguranță", "Standard financiar"],
      de: ["Qualitätsstandard", "Internationaler Umweltmanagementstandard", "Sicherheitsstandard", "Finanzstandard"],
      en: ["Quality standard", "International environmental management standard", "Safety standard", "Financial standard"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ISO 14001 demonstrează angajamentul companiei față de protecția mediului.",
      de: "ISO 14001 zeigt das Engagement des Unternehmens für Umweltschutz.",
      en: "ISO 14001 demonstrates company commitment to environmental protection."
    }
  },
  {
    question: {
      ro: "Ce este raportarea ESG în logistică?",
      de: "Was ist ESG-Berichterstattung in der Logistik?",
      en: "What is ESG reporting in logistics?"
    },
    options: {
      ro: ["Raport financiar", "Raportare pe Environmental, Social, Governance", "Raport tehnic", "Raport de personal"],
      de: ["Finanzbericht", "Berichterstattung zu Umwelt, Soziales, Unternehmensführung", "Technischer Bericht", "Personalbericht"],
      en: ["Financial report", "Reporting on Environmental, Social, Governance", "Technical report", "Staff report"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ESG devine obligatoriu pentru multe companii și influențează relațiile cu clienții.",
      de: "ESG wird für viele Unternehmen obligatorisch und beeinflusst Kundenbeziehungen.",
      en: "ESG is becoming mandatory for many companies and influences client relationships."
    }
  },
  {
    question: {
      ro: "Cum se calculează CO2 per tonă-km?",
      de: "Wie berechnet man CO2 pro Tonnen-km?",
      en: "How is CO2 per ton-km calculated?"
    },
    options: {
      ro: ["Doar distanța", "Emisii totale împărțite la (greutate x distanță)", "Doar greutatea", "Nu se poate calcula"],
      de: ["Nur Entfernung", "Gesamtemissionen geteilt durch (Gewicht x Entfernung)", "Nur Gewicht", "Kann nicht berechnet werden"],
      en: ["Only distance", "Total emissions divided by (weight x distance)", "Only weight", "Cannot be calculated"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Această metrică permite compararea eficienței de mediu între diferite moduri de transport.",
      de: "Diese Metrik ermöglicht Vergleich der Umwelteffizienz zwischen verschiedenen Transportmodi.",
      en: "This metric allows comparison of environmental efficiency between different transport modes."
    }
  },
  {
    question: {
      ro: "Ce sunt creditele de carbon?",
      de: "Was sind CO2-Zertifikate?",
      en: "What are carbon credits?"
    },
    options: {
      ro: ["Împrumuturi bancare", "Unități tranzacționabile reprezentând dreptul de a emite CO2", "Reduceri de preț", "Bonusuri pentru angajați"],
      de: ["Bankdarlehen", "Handelbare Einheiten die das Recht zur CO2-Emission repräsentieren", "Preisnachlässe", "Mitarbeiterboni"],
      en: ["Bank loans", "Tradeable units representing the right to emit CO2", "Price discounts", "Employee bonuses"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Creditele de carbon permit compensarea emisiilor prin investiții în proiecte verzi.",
      de: "CO2-Zertifikate ermöglichen Emissionsausgleich durch Investitionen in grüne Projekte.",
      en: "Carbon credits allow offsetting emissions through investments in green projects."
    }
  },
  {
    question: {
      ro: "Ce este transportul intermodal și beneficiul său de mediu?",
      de: "Was ist intermodaler Transport und sein Umweltvorteil?",
      en: "What is intermodal transport and its environmental benefit?"
    },
    options: {
      ro: ["Doar rutier", "Combinație moduri transport (rutier, feroviar, maritim) reducând emisiile", "Doar feroviar", "Doar aerian"],
      de: ["Nur Straße", "Kombination von Transportmodi (Straße, Schiene, See) zur Emissionsreduzierung", "Nur Schiene", "Nur Luft"],
      en: ["Only road", "Combination of transport modes (road, rail, sea) reducing emissions", "Only rail", "Only air"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Trenul și navele emit mai puțin CO2/t-km decât camioanele pentru distanțe lungi.",
      de: "Zug und Schiffe emittieren weniger CO2/t-km als LKW für lange Strecken.",
      en: "Train and ships emit less CO2/t-km than trucks for long distances."
    }
  },
  {
    question: {
      ro: "Ce este optimizarea încărcării pentru mediu?",
      de: "Was ist Ladeoptimierung für die Umwelt?",
      en: "What is load optimization for environment?"
    },
    options: {
      ro: ["Încărcare minimă", "Maximizarea utilizării capacității vehiculului pentru a reduce curse goale", "Încărcare rapidă", "Încărcare nocturnă"],
      de: ["Minimale Beladung", "Maximierung der Fahrzeugkapazitätsnutzung zur Reduzierung von Leerfahrten", "Schnelle Beladung", "Nachtbeladung"],
      en: ["Minimum loading", "Maximizing vehicle capacity utilization to reduce empty runs", "Fast loading", "Night loading"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Fiecare cursă goală sau parțial încărcată crește amprenta de carbon pe tonă transportată.",
      de: "Jede Leer- oder Teilfahrt erhöht den CO2-Fußabdruck pro transportierter Tonne.",
      en: "Every empty or partially loaded run increases carbon footprint per transported ton."
    }
  },
  {
    question: {
      ro: "Ce obligații de raportare de mediu au companiile de transport?",
      de: "Welche Umweltberichtspflichten haben Transportunternehmen?",
      en: "What environmental reporting obligations do transport companies have?"
    },
    options: {
      ro: ["Niciuna", "Raportare emisii, consum combustibil, deșeuri (variază după mărime)", "Doar financiare", "Doar tehnice"],
      de: ["Keine", "Emissionsberichterstattung, Kraftstoffverbrauch, Abfall (variiert nach Größe)", "Nur finanziell", "Nur technisch"],
      en: ["None", "Emissions reporting, fuel consumption, waste (varies by size)", "Only financial", "Only technical"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Obligațiile de raportare cresc odată cu mărimea companiei și reglementările UE.",
      de: "Berichtspflichten steigen mit Unternehmensgröße und EU-Vorschriften.",
      en: "Reporting obligations increase with company size and EU regulations."
    }
  },
  {
    question: {
      ro: "Ce este poluarea fonică și cum o reduce transportul?",
      de: "Was ist Lärmbelästigung und wie reduziert der Transport sie?",
      en: "What is noise pollution and how does transport reduce it?"
    },
    options: {
      ro: ["Nu există", "Zgomot deranjant, redus prin vehicule silențioase și restricții orare", "Doar muzică tare", "Doar în fabrici"],
      de: ["Gibt es nicht", "Störender Lärm, reduziert durch leise Fahrzeuge und Zeitbeschränkungen", "Nur laute Musik", "Nur in Fabriken"],
      en: ["Doesn't exist", "Disturbing noise, reduced through quiet vehicles and time restrictions", "Only loud music", "Only in factories"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Restricțiile nocturne în multe orașe europene vizează reducerea poluării fonice.",
      de: "Nächtliche Beschränkungen in vielen europäischen Städten zielen auf Lärmreduzierung.",
      en: "Night restrictions in many European cities aim at reducing noise pollution."
    }
  },
  {
    question: {
      ro: "Ce înseamnă fleet modernization pentru mediu?",
      de: "Was bedeutet Flottenmodernisierung für die Umwelt?",
      en: "What does fleet modernization mean for environment?"
    },
    options: {
      ro: ["Vopsire nouă", "Înlocuirea vehiculelor vechi cu altele mai eficiente și mai puțin poluante", "Curățare", "Doar reparații"],
      de: ["Neue Lackierung", "Ersatz alter Fahrzeuge durch effizientere und weniger umweltschädliche", "Reinigung", "Nur Reparaturen"],
      en: ["New paint", "Replacing old vehicles with more efficient and less polluting ones", "Cleaning", "Only repairs"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Vehiculele noi Euro 6 emit semnificativ mai puțin decât cele vechi.",
      de: "Neue Euro 6-Fahrzeuge emittieren deutlich weniger als alte.",
      en: "New Euro 6 vehicles emit significantly less than old ones."
    }
  },
  {
    question: {
      ro: "Ce rol au sistemele telematics în reducerea emisiilor?",
      de: "Welche Rolle spielen Telematiksysteme bei der Emissionsreduzierung?",
      en: "What role do telematics systems play in reducing emissions?"
    },
    options: {
      ro: ["Niciun rol", "Monitorizare consum, optimizare rute, analiză comportament șoferi", "Doar localizare", "Doar comunicare"],
      de: ["Keine Rolle", "Verbrauchsüberwachung, Routenoptimierung, Fahrerverhaltenanalyse", "Nur Ortung", "Nur Kommunikation"],
      en: ["No role", "Consumption monitoring, route optimization, driver behavior analysis", "Only location", "Only communication"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Telematics oferă date pentru îmbunătățirea continuă a eficienței de combustibil.",
      de: "Telematik liefert Daten zur kontinuierlichen Verbesserung der Kraftstoffeffizienz.",
      en: "Telematics provides data for continuous improvement of fuel efficiency."
    }
  },
  {
    question: {
      ro: "Ce este Green Freight Europe?",
      de: "Was ist Green Freight Europe?",
      en: "What is Green Freight Europe?"
    },
    options: {
      ro: ["Companie de transport", "Program de certificare și raportare a performanței de mediu", "Rută verde", "Produs ecologic"],
      de: ["Transportunternehmen", "Zertifizierungs- und Umweltleistungsberichtsprogramm", "Grüne Route", "Ökoprodukt"],
      en: ["Transport company", "Environmental performance certification and reporting program", "Green route", "Eco product"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Green Freight Europe ajută companiile să măsoare și să reducă impactul de mediu.",
      de: "Green Freight Europe hilft Unternehmen, Umweltauswirkungen zu messen und zu reduzieren.",
      en: "Green Freight Europe helps companies measure and reduce environmental impact."
    }
  },
  {
    question: {
      ro: "Ce sunt materialele de ambalare ecologice?",
      de: "Was sind umweltfreundliche Verpackungsmaterialien?",
      en: "What are eco-friendly packaging materials?"
    },
    options: {
      ro: ["Plastic obișnuit", "Materiale reciclabile, biodegradabile sau reutilizabile", "Doar hârtie", "Doar metal"],
      de: ["Normales Plastik", "Recycelbare, biologisch abbaubare oder wiederverwendbare Materialien", "Nur Papier", "Nur Metall"],
      en: ["Regular plastic", "Recyclable, biodegradable or reusable materials", "Only paper", "Only metal"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Ambalajul ecologic reduce deșeurile și impactul de mediu al lanțului de aprovizionare.",
      de: "Umweltfreundliche Verpackung reduziert Abfall und Umweltauswirkungen der Lieferkette.",
      en: "Eco-friendly packaging reduces waste and environmental impact of supply chain."
    }
  },
  {
    question: {
      ro: "Ce este planificarea rutelor verzi?",
      de: "Was ist grüne Routenplanung?",
      en: "What is green route planning?"
    },
    options: {
      ro: ["Rute prin păduri", "Optimizare pentru minimizarea consumului și emisiilor, nu doar distanța", "Rute pe drumuri de pământ", "Rute turistice"],
      de: ["Routen durch Wälder", "Optimierung zur Minimierung von Verbrauch und Emissionen, nicht nur Entfernung", "Routen auf Feldwegen", "Touristische Routen"],
      en: ["Routes through forests", "Optimization for minimizing consumption and emissions, not just distance", "Routes on dirt roads", "Tourist routes"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Rutele optime pentru mediu pot diferi de cele mai scurte ca distanță.",
      de: "Umweltoptimale Routen können von den kürzesten Entfernungsrouten abweichen.",
      en: "Environmentally optimal routes may differ from shortest distance routes."
    }
  },
  {
    question: {
      ro: "Ce este sistemul EU ETS pentru transport?",
      de: "Was ist das EU ETS-System für den Transport?",
      en: "What is the EU ETS system for transport?"
    },
    options: {
      ro: ["Sistem de navigație", "Sistem de tranzacționare a emisiilor care va include și transportul maritim", "Sistem de taxare", "Sistem de comunicare"],
      de: ["Navigationssystem", "Emissionshandelssystem das auch Seeverkehr einschließen wird", "Steuersystem", "Kommunikationssystem"],
      en: ["Navigation system", "Emissions trading system that will include maritime transport", "Tax system", "Communication system"]
    },
    correctIndex: 1,
    explanation: {
      ro: "ETS va crește costul emisiilor și va stimula investițiile în tehnologii verzi.",
      de: "ETS wird Emissionskosten erhöhen und Investitionen in grüne Technologien stimulieren.",
      en: "ETS will increase emissions cost and stimulate investments in green technologies."
    }
  },
  {
    question: {
      ro: "Ce este well-to-wheel vs. tank-to-wheel?",
      de: "Was ist Well-to-Wheel vs. Tank-to-Wheel?",
      en: "What is well-to-wheel vs. tank-to-wheel?"
    },
    options: {
      ro: ["Tipuri de roți", "Metode de calcul emisii: de la sursă vs. doar la utilizare", "Tipuri de combustibil", "Tipuri de vehicule"],
      de: ["Radtypen", "Emissionsberechnungsmethoden: von Quelle vs. nur bei Nutzung", "Kraftstofftypen", "Fahrzeugtypen"],
      en: ["Wheel types", "Emission calculation methods: from source vs. only at use", "Fuel types", "Vehicle types"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Analiza completă (well-to-wheel) include și emisiile din producția combustibilului.",
      de: "Vollständige Analyse (Well-to-Wheel) umfasst auch Emissionen aus der Kraftstoffproduktion.",
      en: "Complete analysis (well-to-wheel) includes emissions from fuel production too."
    }
  },
  {
    question: {
      ro: "Ce sunt obiectivele Fit for 55 pentru transport?",
      de: "Was sind die Fit for 55-Ziele für den Transport?",
      en: "What are Fit for 55 objectives for transport?"
    },
    options: {
      ro: ["Viteză 55 km/h", "Reducere emisii cu 55% până în 2030 față de 1990", "55 vehicule", "55 țări"],
      de: ["55 km/h Geschwindigkeit", "55% Emissionsreduzierung bis 2030 gegenüber 1990", "55 Fahrzeuge", "55 Länder"],
      en: ["55 km/h speed", "55% emission reduction by 2030 vs 1990", "55 vehicles", "55 countries"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Fit for 55 impune schimbări majore în transportul european până în 2030.",
      de: "Fit for 55 erfordert große Änderungen im europäischen Transport bis 2030.",
      en: "Fit for 55 requires major changes in European transport by 2030."
    }
  },
  {
    question: {
      ro: "Ce este last-mile delivery ecologic?",
      de: "Was ist umweltfreundliche Last-Mile-Lieferung?",
      en: "What is eco-friendly last-mile delivery?"
    },
    options: {
      ro: ["Livrare lentă", "Livrare finală cu vehicule electrice, biciclete sau cargo bikes", "Livrare lungă", "Livrare scumpă"],
      de: ["Langsame Lieferung", "Endlieferung mit Elektrofahrzeugen, Fahrrädern oder Lastenrädern", "Lange Lieferung", "Teure Lieferung"],
      en: ["Slow delivery", "Final delivery with electric vehicles, bicycles or cargo bikes", "Long delivery", "Expensive delivery"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Last-mile urban este ideal pentru soluții zero emisii datorită distanțelor scurte.",
      de: "Städtische Last-Mile ist ideal für Null-Emissions-Lösungen wegen kurzer Entfernungen.",
      en: "Urban last-mile is ideal for zero-emission solutions due to short distances."
    }
  },
  {
    question: {
      ro: "Ce înseamnă decarbonizare în transport?",
      de: "Was bedeutet Dekarbonisierung im Transport?",
      en: "What does decarbonization mean in transport?"
    },
    options: {
      ro: ["Eliminarea cărbunelui", "Tranziția către surse de energie cu emisii zero sau foarte mici de CO2", "Reducerea greutății", "Eliminarea metalului"],
      de: ["Beseitigung von Kohle", "Übergang zu Energiequellen mit null oder sehr niedrigen CO2-Emissionen", "Gewichtsreduzierung", "Metallbeseitigung"],
      en: ["Eliminating coal", "Transition to energy sources with zero or very low CO2 emissions", "Weight reduction", "Metal elimination"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Decarbonizarea este obiectivul principal al politicii europene de transport.",
      de: "Dekarbonisierung ist das Hauptziel der europäischen Verkehrspolitik.",
      en: "Decarbonization is the main objective of European transport policy."
    }
  },
  {
    question: {
      ro: "Ce rol are aerodinamica în eficiența vehiculelor?",
      de: "Welche Rolle spielt Aerodynamik bei der Fahrzeugeffizienz?",
      en: "What role does aerodynamics play in vehicle efficiency?"
    },
    options: {
      ro: ["Niciun rol", "Reduce rezistența la aer, scăzând consumul la viteze mari", "Doar estetică", "Doar stabilitate"],
      de: ["Keine Rolle", "Reduziert Luftwiderstand, senkt Verbrauch bei hohen Geschwindigkeiten", "Nur Ästhetik", "Nur Stabilität"],
      en: ["No role", "Reduces air resistance, lowering consumption at high speeds", "Only aesthetics", "Only stability"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Îmbunătățirile aerodinamice pot reduce consumul cu până la 10%.",
      de: "Aerodynamische Verbesserungen können den Verbrauch um bis zu 10% senken.",
      en: "Aerodynamic improvements can reduce consumption by up to 10%."
    }
  },
  {
    question: {
      ro: "Ce este biodieselul și limitările sale?",
      de: "Was ist Biodiesel und seine Grenzen?",
      en: "What is biodiesel and its limitations?"
    },
    options: {
      ro: ["Diesel verde", "Combustibil din surse biologice, cu limitări de amestec și disponibilitate", "Diesel sintetic", "Diesel de calitate"],
      de: ["Grüner Diesel", "Kraftstoff aus biologischen Quellen, mit Mischungs- und Verfügbarkeitsbeschränkungen", "Synthetischer Diesel", "Qualitätsdiesel"],
      en: ["Green diesel", "Fuel from biological sources, with blending and availability limitations", "Synthetic diesel", "Quality diesel"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Biodieselul reduce emisiile dar are limitări tehnice și de sustenabilitate.",
      de: "Biodiesel reduziert Emissionen hat aber technische und Nachhaltigkeitsgrenzen.",
      en: "Biodiesel reduces emissions but has technical and sustainability limitations."
    }
  },
  {
    question: {
      ro: "Cum poate un disponent contribui la transportul verde?",
      de: "Wie kann ein Disponent zum grünen Transport beitragen?",
      en: "How can a dispatcher contribute to green transport?"
    },
    options: {
      ro: ["Nu poate contribui", "Optimizare rute, consolidare încărcări, selectare transportatori eficienți", "Doar prin reclamații", "Doar prin raportare"],
      de: ["Kann nicht beitragen", "Routenoptimierung, Ladungskonsolidierung, Auswahl effizienter Frachtführer", "Nur durch Beschwerden", "Nur durch Berichterstattung"],
      en: ["Cannot contribute", "Route optimization, load consolidation, selecting efficient carriers", "Only through complaints", "Only through reporting"]
    },
    correctIndex: 1,
    explanation: {
      ro: "Disponentul influențează direct eficiența și impactul de mediu al fiecărui transport.",
      de: "Der Disponent beeinflusst direkt Effizienz und Umweltauswirkungen jedes Transports.",
      en: "Dispatcher directly influences efficiency and environmental impact of each transport."
    }
  }
];
